# Generated by Django 2.2 on 2019-12-08 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('description', models.TextField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('document', models.FileField(upload_to='book/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank='False', max_length=200)),
                ('description', models.TextField(blank='True')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('document', models.FileField(upload_to='topic/%Y/%m/%d')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='engine.Book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.ManyToManyField(related_name='subjects', to='engine.Subject'),
        ),
    ]
