# Generated by Django 2.2.8 on 2019-12-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_auto_20191218_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.TextField(max_length=50, unique=True),
        ),
    ]
