# Generated by Django 2.2.8 on 2020-01-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_auto_20191218_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
