# Generated by Django 2.2.8 on 2020-01-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_auto_20200121_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='engine.Topic'),
        ),
    ]
