# Generated by Django 2.2.8 on 2020-01-21 21:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_auto_20200121_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
