# Generated by Django 2.2.8 on 2020-01-21 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0008_tag_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnsafeTag',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('engine.tag',),
        ),
    ]
